version: 1.0.{build}
branches:
  except:
  - /^release$|^release-\d-\d-x$/
build_cloud: libcc-20
image: libcc-20-vs2017
environment:
  DISABLE_CRASH_REPORTER_TESTS: true
  ELECTRON_ENABLE_LOGGING: true
build_script:
  - ps: git config --global core.longpaths true
  - ps: cd ..
  - ps: New-Item -Name src -ItemType directory
  - ps: Move-Item $env:APPVEYOR_BUILD_FOLDER -Destination src\electron
  - ps: $env:CHROMIUM_BUILDTOOLS_PATH="$pwd\src\buildtools"
  - ps: >-
        gclient config
        --name "src\electron"
        --unmanaged
        --cache-dir "C:\Users\electron\libcc_cache"
        "https://github.com/electron/electron"
        2>$null

        Write-Output "hmmm"
  - ps: gclient sync --with_branch_heads --with_tags
  - ps: cd src
  - ps: gn gen out\Default '--args=import(\"//electron/build/args/debug.gn\")'
  - ps: ninja -C out\Default electron:electron_app
test_script:
  - ps: ninja -C out/Default electron/build/node:headers
  - ps: |
      $env:npm_config_nodedir="$pwd/out/Default/gen/node_headers"
      Push-Location
      cd electron/spec
      npm install
      Pop-Location
  - ps: python -c 'import subprocess; subprocess.check_call([\"./out/Default/electron.exe\", \"electron/spec\", \"--ci\"])'
  # TODO(nornagon): verify-ffmpeg step
artifacts:
- path: test-results.xml
  name: test-results.xml
